name: Set-Prefix-For-PAF
version: ${project.version}
author: Simonsator
depends: [PartyAndFriends]
main: de.simonsator.partyandfriends.extensions.displaynamecommand.DNCPlugin
description: An add-on for party and friends to let your players set their own prefixes